name: Tag Release and Changelog

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag version (e.g., v1.0.0)'
        required: true
        type: string

permissions:
  contents: write

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Get tag
        id: tag
        run: |
          if [ "${{ github.event_name }}" = "push" ]; then
            echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          else
            echo "TAG=${{ inputs.tag }}" >> $GITHUB_OUTPUT
          fi
          
      - name: Get previous tag
        id: prev_tag
        run: |
          PREV_TAG=$(git describe --tags --abbrev=0 $(git rev-list --tags --skip=1 --max-count=1) 2>/dev/null || echo "")
          echo "PREV_TAG=${PREV_TAG}" >> $GITHUB_OUTPUT
          
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Generate changelog for this release
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fromTag: ${{ steps.prev_tag.outputs.PREV_TAG }}
          toTag: ${{ steps.tag.outputs.TAG }}
          includeInvalidCommits: true
          excludeTypes: build,docs,style,other
          
      - name: Update CHANGELOG.md
        run: |
          # Create or prepend to CHANGELOG.md
          if [ ! -f CHANGELOG.md ]; then
            echo "# Changelog" > CHANGELOG.md
            echo "" >> CHANGELOG.md
            echo "All notable changes to this project will be documented in this file." >> CHANGELOG.md
            echo "" >> CHANGELOG.md
          fi
          
          # Create temporary file with new release notes
          echo "## [${{ steps.tag.outputs.TAG }}] - $(date +%Y-%m-%d)" > temp_changelog.md
          echo "" >> temp_changelog.md
          echo "${{ steps.changelog.outputs.changes }}" >> temp_changelog.md
          echo "" >> temp_changelog.md
          
          # Append existing changelog
          tail -n +2 CHANGELOG.md >> temp_changelog.md
          
          # Replace with new file
          echo "# Changelog" > CHANGELOG.md
          echo "" >> CHANGELOG.md
          echo "All notable changes to this project will be documented in this file." >> CHANGELOG.md
          echo "" >> CHANGELOG.md
          cat temp_changelog.md >> CHANGELOG.md
          rm temp_changelog.md
          
      - name: Commit and push changelog
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add CHANGELOG.md
          git commit -m "docs: update CHANGELOG.md for ${{ steps.tag.outputs.TAG }} [skip ci]"
          git push origin HEAD:main
          
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.TAG }}
          body: ${{ steps.changelog.outputs.changes }}
          draft: false
          prerelease: false